### ISSUE TITLE
Is there a way for ckb *not* to handle non-Corsair keys?

### ISSUE THREAD

**Issue by thblt** [ccMSC/ckb#135]
First, thanks for ckb — it's great to have the macro keys usable on OSX. 

This is more an enhancement request than a bug report : It would be great if ckb was able to handle the special Corsair keys (G1-18, M1-3, and so on) but leave the rest as is (that would allow, for example, software like Karabiner to transform keys, etc). 

If that's not possible, maybe allowing custom layouts would allow to achieve the same result (either with an integrated layout editor, or by loading an external layout. On OSX, [Ukelele](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele) may be used to prepare them.)

Thanks

**Comment by ccMSC** [comment]
FWIW Ukelele *should* still work with ckb, since ckb just handles input and doesn't dictate keyboard layouts to the OS.

To answer the original question, I tried something like this at one point, but the keyboard hardware just doesn't work reliably when you ask it to do that. So unfortunately I don't think it's possible.

**Comment by thblt** [comment]
Thanks for your answer ! I assumed keyboard layouts were somehow hardcoded in ckb, since the GUI asks you to choose one. Sorry about the dumb question then, I should have tried first.
