### ISSUE TITLE
Keys ghosting when using high FPS settings

### ISSUE THREAD

**Issue by Xelethor** [ccMSC/ckb#22]
Setting the frame rate option to 60 FPS results in some random key ghosting when pressing the same key twice very fast, for example pushing twice the back space removes only 1 character. Also happens for 50 FPS, and doesn't seem to happen at all with 30 FPS.

I'm using a K70 RGB with US layout.

**Comment by ccMSC** [comment]
This is a hardware issue (and is the reason why the default setting is 30). It appeared in the 1.15 firmware update. If you happen to have a copy of the 1.13 FW for your board, you can revert to that in order to fix it. Otherwise you'll have to leave the FPS at 30 for now. I've also found that increasing the poll interval to 8ms sometimes solves it, but not always.
