### ISSUE TITLE
Animations only work when UI running

### ISSUE THREAD

**Issue by jaufgang** [ccMSC/ckb#51]
Running pre-compiled version on OSX, with daemon installed.

When UI is open, animations work perfectly.  When I quit the UI, animations stop responding to keypress events.

Is this the expected behaviour, that UI app must be opened and kept running in the background?   To me it would make more sense to have the code to respond to keypress events and activate animations as part of the daemon, and to require the UI only for editing profiles/modes or changing other settings.

**Comment by ccMSC** [comment]
This is correct. The daemon only talks to the keyboard, it doesn't handle animations. Since the animations can't be handled at a hardware level, they require the GUI (also, the animations are actually their own programs and I have plans to implement custom animations via python, so having the daemon run them would be a serious security risk).
