### ISSUE TITLE
How can I help you with this project?

### ISSUE THREAD

**Issue by Keridos** [ccMSC/ckb#94]
Hi there,

I have a K95 RGB and noticed that it does not work good under linux. Since I know a bit about programming and you have not yet written any info on how to contribute to this project I am creating this issue. Can you maybe set up a wiki page that describes how to setup a dev environment for this and describe briefly how this whole thing works? If you did that I might be able to help you develop this a bit.

**Comment by ccMSC** [comment]
There's a somewhat-complete list of planned features in the "Roadmap" section near the bottom of the readme.

Other misc. things that need doing:

1. Restricting access to the device nodes to only the user who has physical access to the keyboard. See: https://github.com/ccMSC/ckb/issues/73
2. Storing the global modifier mappings (e.g. Cmd <-> Ctrl) at a driver level so that they can be restored even when the GUI is not running. On OSX there is a system registry for this which should be read/written accordingly. On Linux it should be stored in a file somewhere.
3. https://github.com/ccMSC/ckb/issues/64
4. Related, I'd like to be able to animate a specific group of keys, but have the trigger for the animation be a separate group. Like, say there's a ripple the covers the entire home row. But the only keys that actually trigger the ripple are A and S. Currently the trigger keys are always the same as the animated keys.
5. This feature request: http://forum.corsair.com/v3/showpost.php?p=787564&postcount=362

That's all I can think of off the top of my head. I'm sure there are more things to do but I mostly track features based on how often they get requested. Currently the most requested feature is importing of CUE profiles, but it's going to be a long process, especially because ckb still doesn't have 100% of the feature coverage that CUE does. Let me know if any of them interest you :)
